### PR TITLE
New setuptools py3

### PR DESCRIPTION
**Pull request by goschtl**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
I tested it and it works. Thanks!

Tox works locally too.
In extra commits I have updated tox to run on more Python versions, and I have enabled GitHub Actions. Let's see how that goes.

**Comment by mauritsvanrees** [comment]
The GitHub Actions don't seem to do anything. Let's merge.

**Comment by mauritsvanrees** [comment]
I have released 1.1.0.

**Comment by goschtl** [comment]
@mauritsvanrees Thanks for releasing....

**Pull request merged**
