### PR TITLE
ntfsutils are not needed in py3

### PR DESCRIPTION
**Pull request by nilshofer**

### CODE REVIEW

**Comment by jensens** [comment]
FTR: os.symlink et all supports Windows since Python 3.2 - see https://docs.python.org/3/library/os.html#os.symlink

**Comment by mauritsvanrees** [comment]
Can we have a new release with this?
PyPI maintainers are, among others: @davisagli @fschulze @MatthewWilkes .
Can you make the collective and/or plone user owner/maintainer as well, please? Then I can make a release.

**Comment by mauritsvanrees** [comment]
BTW, I noticed that tag 0.16 from 2013 was missing. Fixed now. And I have updated the version on master to be 1.0.0.  The code seems stable. :-)

**Comment by davisagli** [comment]
@mauritsvanrees you are now an Owner on PyPI. Thanks!

**Comment by davisagli** [comment]
@mauritsvanrees oh, just saw you asked for plone as owner, not yourself. I'll fix that...

**Comment by mauritsvanrees** [comment]
Thank you!
I have released version 1.0.0 to PyPI.

**Pull request merged**
